# pymysql 테스트

In [1]:
import pymysql

In [2]:
conn = pymysql.connect(
    host='localhost', user='root', password='1234', db='my_db', charset='utf8'
)
conn

In [3]:
cursor = conn.cursor()
cursor

In [4]:
sql_query = '''SELECT ENAME, SAL, JOB
FROM EMP;
'''
cursor.execute(sql_query)
result = cursor.fetchall()
result

(('SMITH', Decimal('800.00'), 'CLERK'),
 ('ALLEN', Decimal('1600.00'), 'SALESMAN'),
 ('WARD', Decimal('1250.00'), 'SALESMAN'),
 ('JONES', Decimal('2975.00'), 'MANAGER'),
 ('MARTIN', Decimal('1250.00'), 'SALESMAN'),
 ('BLAKE', Decimal('2850.00'), 'MANAGER'),
 ('CLARK', Decimal('2450.00'), 'MANAGER'),
 ('SCOTT', Decimal('3000.00'), 'ANALYST'),
 ('KING', Decimal('5000.00'), 'PRESIDENT'),
 ('TURNER', Decimal('1500.00'), 'SALESMAN'),
 ('ADAMS', Decimal('1100.00'), 'CLERK'),
 ('JAMES', Decimal('950.00'), 'CLERK'),
 ('FORD', Decimal('3000.00'), 'ANALYST'),
 ('MILLER', Decimal('1300.00'), 'CLERK'))

In [5]:
import pandas as pd
pd.DataFrame(result)

         0        1          2
0    SMITH   800.00      CLERK
1    ALLEN  1600.00   SALESMAN
2     WARD  1250.00   SALESMAN
3    JONES  2975.00    MANAGER
4   MARTIN  1250.00   SALESMAN
5    BLAKE  2850.00    MANAGER
6    CLARK  2450.00    MANAGER
7    SCOTT  3000.00    ANALYST
8     KING  5000.00  PRESIDENT
9   TURNER  1500.00   SALESMAN
10   ADAMS  1100.00      CLERK
11   JAMES   950.00      CLERK
12    FORD  3000.00    ANALYST
13  MILLER  1300.00      CLERK

In [6]:
import MySQLdb
# MySQL 서버에 연결
db_config = {
'host' :'localhost',  # 호스트 이름
'user' : 'root', # MySQL 사용자 이름
'passwd' : '1234', # MySQL 사용자 비밀번호
'db' : 'my_db', # 연결할 데이터베이스 이름
'charset' : 'utf8'
}

In [7]:
try:
    conn = MySQLdb.connect(**db_config) # 커서 생성
    cursor = conn.cursor() # 쿼리 실행 예시
    sql_query = "SELECT * FROM dept"
    cursor.execute(sql_query) # 쿼리 결과 가져오기
    result = cursor.fetchall() # 결과 출력
    for row in result:
        print(row)
except MySQLdb.Error as e:
    print(f"Error: {e}")
finally: # 연결과 커서 닫기
    cursor.close()
    conn.close()

(10, 'ACCOUNTING', 'NEW YORK')
(20, 'RESEARCH', 'DALLAS')
(30, 'SALES', 'CHICAGO')
(40, 'OPERATIONS', 'BOSTON')

In [8]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:1234@localhost/my_db")
engine

Engine(mysql+pymysql://root:***@localhost/my_db)

In [9]:
df = pd.read_sql("SHOW TABLES IN MY_DB;", engine)
df.head()

  Tables_in_my_db
0            dept
1             emp
2      products_1
3        salgrade

products 모델을 정의하고 연결

In [10]:
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

In [11]:
# ORM 기본 클래스 생성
Base = declarative_base()

C:\Users\Admin\AppData\Local\Temp\ipykernel_11120\2681860153.py:2: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [12]:
# products 테이블 정의
class Product(Base):
    __tablename__ = 'products_1'

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False)
    price = Column(Integer, nullable=False)
    stock = Column(Integer, nullable=False)

    def __repr__(self):
        return f"<Product(id={self.id}, name='{self.name}', price={self.price}, stock={self.stock})>"

In [13]:
# 테이블 생성
Base.metadata.create_all(engine)

세션 설정

In [14]:
Session = sessionmaker(bind=engine)
session = Session()

CREATE : 상품 등록

In [15]:
def add_product(name, price, stock):
    new_product = Product(name=name, price=price, stock=stock)
    session.add(new_product)
    session.commit()
    print(f"🆕 '{name}' 상품이 등록되었습니다!")


add_product("롤리팝", 500, 10)
add_product("핫초코", 2000, 10)

🆕 '롤리팝' 상품이 등록되었습니다!
🆕 '핫초코' 상품이 등록되었습니다!

READ : 상품 조회

In [16]:
def list_products():
    products = session.query(Product).all()   #SELECT
    for p in products:
        print(p)

list_products()

<Product(id=1, name='롤리팝', price=1500, stock=10)>
<Product(id=2, name='핫초코', price=3000, stock=10)>
<Product(id=4, name='핫초코', price=2000, stock=10)>
<Product(id=5, name='롤리팝', price=500, stock=10)>
<Product(id=6, name='핫초코', price=2000, stock=10)>

UPDATE : 가격 수정

In [17]:
def update_price(product_id, new_price):
    product = session.query(Product).get(product_id)
    if product:
        product.price = new_price
        session.commit()
        print(f"💸 {product.name}의 가격이 {new_price}원으로 변경되었습니다.")
    else:
        print("❌ 해당 상품이 존재하지 않습니다.")

update_price(2, 3000)

💸 핫초코의 가격이 3000원으로 변경되었습니다.

C:\Users\Admin\AppData\Local\Temp\ipykernel_11120\4289321564.py:2: LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  product = session.query(Product).get(product_id)

DELETE : 상품 삭제

In [18]:
def delete_product(product_id):
    product = session.query(Product).get(product_id)
    if product:
        session.delete(product)
        session.commit()
        print(f"🗑️ '{product.name}' 상품이 삭제되었습니다.")
    else:
        print("❌ 해당 상품이 존재하지 않습니다.")
        
delete_product(3)

❌ 해당 상품이 존재하지 않습니다.

C:\Users\Admin\AppData\Local\Temp\ipykernel_11120\652162444.py:2: LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  product = session.query(Product).get(product_id)

세션의 반납

In [19]:
try:
    # 작업
    product = session.query(Product).get(1)
    product.price += 500
    session.commit()
except Exception as e:
    session.rollback()
    print("예외 발생, 롤백:", e)
finally:
    session.close()
    print("세션 종료")

세션 종료

C:\Users\Admin\AppData\Local\Temp\ipykernel_11120\1734247740.py:3: LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  product = session.query(Product).get(1)